name: final_ecommerce
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0-70.0.dev

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.4
  firebase_auth: ^5.5.0
  intl: ^0.19.0
  fluttertoast: ^8.2.2
  provider: ^6.1.2
  url_launcher: ^6.3.1
  http: ^1.3.0
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  http_parser: ^4.1.2
  path: ^1.9.1
  photo_view: ^0.15.0
  shared_preferences: ^2.5.2
  bcrypt: ^1.1.3
  rxdart: ^0.28.0
  flutter_rating_bar: ^4.0.0
  fl_chart: ^0.70.2
  syncfusion_flutter_charts: ^20.4.48
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
gi  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/categories/
