// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNnHtqDSM5s1m0bSUgIRqnKblKaIHEVH4',
    appId: '1:185749955692:web:d6e22f0cd4d487ad956449',
    messagingSenderId: '185749955692',
    projectId: 'e-commerce-flutter-6762d',
    authDomain: 'e-commerce-flutter-6762d.firebaseapp.com',
    storageBucket: 'e-commerce-flutter-6762d.firebasestorage.app',
    measurementId: 'G-FK4XPBLQ7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKpg0Rt9D5Hm08U5B7iNBFOizKfLifO84',
    appId: '1:185749955692:android:b8be02e57cfcc442956449',
    messagingSenderId: '185749955692',
    projectId: 'e-commerce-flutter-6762d',
    storageBucket: 'e-commerce-flutter-6762d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqtMGpQG2j4HicZgSg11mEb5od8-4Phe0',
    appId: '1:185749955692:ios:34dc873afbcfe3d4956449',
    messagingSenderId: '185749955692',
    projectId: 'e-commerce-flutter-6762d',
    storageBucket: 'e-commerce-flutter-6762d.firebasestorage.app',
    iosBundleId: 'com.example.finalEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqtMGpQG2j4HicZgSg11mEb5od8-4Phe0',
    appId: '1:185749955692:ios:34dc873afbcfe3d4956449',
    messagingSenderId: '185749955692',
    projectId: 'e-commerce-flutter-6762d',
    storageBucket: 'e-commerce-flutter-6762d.firebasestorage.app',
    iosBundleId: 'com.example.finalEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNnHtqDSM5s1m0bSUgIRqnKblKaIHEVH4',
    appId: '1:185749955692:web:d6e22f0cd4d487ad956449',
    messagingSenderId: '185749955692',
    projectId: 'e-commerce-flutter-6762d',
    authDomain: 'e-commerce-flutter-6762d.firebaseapp.com',
    storageBucket: 'e-commerce-flutter-6762d.firebasestorage.app',
    measurementId: 'G-FK4XPBLQ7D',
  );
}
